services:
  telegram_bot:
    build: .
    container_name: vuzoparser_bot
    env_file:
      -  .env
    volumes:
      - .:/app
    restart: always  # <-- Если бот упадет, докер сам его поднимет
    dns:
      - 8.8.8.8      # <-- DNS от Google (всегда стабильный)
      - 1.1.1.1      # <-- DNS от Cloudflare
    command: sh -c "uv run alembic upgrade head && uv run main.py"