"""add_user_code_to_user_directions

Revision ID: c12e5419145c
Revises: 418006bb708f
Create Date: 2026-07-07 13:35:33.074192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12e5419145c'
down_revision: Union[str, Sequence[str], None] = '418006bb708f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_directions', sa.Column('user_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_directions', 'user_code')
    # ### end Alembic commands ###
